### ISSUE TITLE
Release of the LH2TS Code

### ISSUE THREAD

**Issue by db-code-rabbit** [LLNL/LH2Transfer#3]
Hi,

Below is the link to the new release of the LH2TS Code ([LLNL/LH2Transfer](https://github.com/LLNL/LH2Transfer))
Test it by following  the instructions. 

[Release of the LH2TS Code](https://github.com/db-code-rabbit/Release-LLNL-LH2Transfer)

**Comment by datum12345** [comment]
Thanks

**Comment by datum12345** [comment]
I will try the new version of ([LLNL/LH2Transfer](https://github.com/LLNL/LH2Transfer)).
